[package]
name = "mcdh-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
directories.workspace = true
fs2.workspace = true
jsonc-parser.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true
walkdir.workspace = true
zip.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
